version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: test_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1402
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1402
    ports:
      - "8080:80"

volumes:
  db_data:
